### ISSUE TITLE
Route53: Syncing has an exception when printing ignored records

### ISSUE THREAD

**Issue by msiebert** [lucidsoftware/cumulus#51]
stack trace:

```
lib/route53/models/RecordDiff.rb:71:in `aws_name': undefined method `type' for #<Hash:0x0000000220abc8> (NoMethodError)
  from lib/route53/manager/Manager.rb:84:in `block (2 levels) in update'
  from lib/route53/manager/Manager.rb:83:in `each'
  from lib/route53/manager/Manager.rb:83:in `block in update'
  from lib/route53/manager/Manager.rb:67:in `each'
  from lib/route53/manager/Manager.rb:67:in `update'
  from lib/common/manager/Manager.rb:120:in `sync_difference'
  from lib/common/manager/Manager.rb:58:in `block in sync_one'
  from lib/common/manager/Manager.rb:79:in `call'
  from lib/common/manager/Manager.rb:79:in `block in each_difference'
  from lib/common/manager/Manager.rb:75:in `each'
  from lib/common/manager/Manager.rb:75:in `each_difference'
  from lib/common/manager/Manager.rb:58:in `sync_one'
  from bin/cumulus.rb:148:in `route53'
  from bin/cumulus.rb:268:in `<main>'
```

**Comment by msiebert** [comment]
While I'm at it, I'm gonna make it so ignored records when syncing can be condensed with the `"print-all-ignored"` configuration value.
