### ISSUE TITLE
Empty IAM user error

### ISSUE THREAD

**Issue by msiebert** [lucidsoftware/cumulus#71]
If you create a new user, and the user doesn't have any policies attached to them, upon creation, no policy will be created, but Cumulus will try to attach it anyways.

```
cumulus iam users sync
creating name...
    updating policy CUMULUS-name...
/var/lib/gems/1.9.1/gems/aws-sdk-core-2.1.7/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': The user policy with name CUMULUS-name cannot be found. (Aws::IAM::Errors::NoSuchEntity)
    from /var/lib/gems/1.9.1/gems/aws-sdk-core-2.1.7/lib/aws-sdk-core/plugins/param_converter.rb:21:in `call'
    from /var/lib/gems/1.9.1/gems/aws-sdk-core-2.1.7/lib/seahorse/client/plugins/response_target.rb:21:in `call'
    from /var/lib/gems/1.9.1/gems/aws-sdk-core-2.1.7/lib/seahorse/client/request.rb:70:in `send_request'
    from /var/lib/gems/1.9.1/gems/aws-sdk-core-2.1.7/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
    from /var/lib/gems/1.9.1/gems/aws-sdk-resources-2.1.7/lib/aws-sdk-resources/request.rb:24:in `call'
    from /var/lib/gems/1.9.1/gems/aws-sdk-resources-2.1.7/lib/aws-sdk-resources/operations.rb:41:in `call'
    from /var/lib/gems/1.9.1/gems/aws-sdk-resources-2.1.7/lib/aws-sdk-resources/operation_methods.rb:19:in `block in add_operation'
    from /home/derrick/.cumulus/lib/iam/manager/IamResource.rb:257:in `update_policy'
    from /home/derrick/.cumulus/lib/iam/manager/IamResource.rb:181:in `update'
    from /home/derrick/.cumulus/lib/iam/manager/IamResource.rb:239:in `sync_difference'
    from /home/derrick/.cumulus/lib/iam/manager/IamResource.rb:114:in `block in sync'
    from /home/derrick/.cumulus/lib/iam/manager/IamResource.rb:220:in `call'
    from /home/derrick/.cumulus/lib/iam/manager/IamResource.rb:220:in `block in each_difference'
    from /home/derrick/.cumulus/lib/iam/manager/IamResource.rb:218:in `each'
    from /home/derrick/.cumulus/lib/iam/manager/IamResource.rb:218:in `each_difference'
    from /home/derrick/.cumulus/lib/iam/manager/IamResource.rb:114:in `sync'
    from /home/derrick/.cumulus/bin/cumulus.rb:63:in `iam'
    from /home/derrick/.cumulus/bin/cumulus.rb:365:in `<main>'
```

**Comment by msiebert** [comment]
fixed by @JeffreyHWright in #84
